### ISSUE TITLE
某些中文名字乱码

### ISSUE THREAD

**Issue by XiaoNiFF** [moyuanz/hahajing#2]
![20180718104619](https://user-images.githubusercontent.com/10608527/42856507-207a781e-8a78-11e8-9858-28993401d7ff.png)

**Comment by moyuanz** [comment]
可能是源数据就是乱的
![default](https://user-images.githubusercontent.com/37684059/42889476-1e669296-8add-11e8-82a3-c76df7588d1e.png)

**Comment by XiaoNiFF** [comment]
是的，有的是好的，也不影响。
